name: Snyk Security Scan
permissions:
  contents: read
  pull-requests: write
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Run Snyk to check for code vulnerabilities
        uses: snyk/actions/node@master
        with:
          args: 'test --all-dependencies --all-licenses --all-vulnerabilities'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
